# Generated by Django 2.2.5 on 2019-12-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
