# Generated by Django 2.2.5 on 2019-12-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider1', models.ImageField(default='', upload_to='shop/images')),
                ('slider2', models.ImageField(default='', upload_to='shop/images')),
                ('slider3', models.ImageField(default='', upload_to='shop/images')),
                ('slider4', models.ImageField(default='', upload_to='shop/images')),
                ('slider5', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
