# Generated by Django 2.2.5 on 2019-12-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20191223_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
